# Generated by Django 2.2.4 on 2019-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aman', max_length=100)),
                ('section', models.CharField(default='A', max_length=10)),
            ],
        ),
    ]
